server {
    listen 80;
    server_name memlayer.ru www.memlayer.ru;

    root /opt/memlayer/deploy/msk/site;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl http2;
    server_name memlayer.ru www.memlayer.ru;

    ssl_certificate /etc/letsencrypt/live/memlayer.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/memlayer.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /opt/memlayer/deploy/msk/site;
    index index.html;

    access_log /var/log/nginx/memlayer.ru.access.log;
    error_log /var/log/nginx/memlayer.ru.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
